name: Build Docker Image

on:
  push:
    branches:
      - "!main"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build . \
          --tag "ghcr.io/${{ github.repository_owner }}/${GITHUB_REPOSITORY#*/}:latest" \
          --tag "ghcr.io/${{ github.repository_owner }}/${GITHUB_REPOSITORY#*/}:${{ github.sha }}"
